# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~# arankUserBot #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# Copyright (C) 2020-2023 by CoderXKrishna@Github.

# This file is part of: https://github.com/CoderXKrishna/arankuserbot
# and is released under the "GNU v3.0 License Agreement".

# Please see: https://github.com/CoderXKrishna/arankuserbot/blob/master/LICENSE
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

version: '3.3'

services:
 app:
    container_name: arank
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 -m userbot
    restart: on-failure
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/arankuserbot
    depends_on:
      - db

 db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=arankuserbot
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
  botdata:
    driver: local

